[tool.ruff]
line-length = 120
target-version = "py310"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "data_seeder.py",
    "scripts/*",
]

[tool.mypy]
ignore_missing_imports = true
explicit_package_bases = true
